"%s" = "%s" # Do not delete :)
module_base = "Base"

err_web_param_wrong = "A method parameter could not parse for cmd %s. In context '%s'"
err_param = "Invalid value for parameter %s: %s"

and = "and"
decimal_point = '.'
thousands_sep = ','

######################
# Method permissions #
######################
err_type = "This method is restricted to %s."

################
# Server Error #
################
mt_base_server_error = "Server Error"
md_base_server_error = "The server made a booboo... probably broken code or a configuration error."

##############
# Fileserver #
##############
mt_base_fileserver = "File Download"
md_base_fileserver = "Download a file from this website."
