"%s" = "%s" # Do not delete :)
module_base = "Base"

err_web_param_wrong = "A method parameter could not parse for cmd %s. In context '%s'"
err_param = "Invalid value for parameter %s: %s"
err_method_connector_not_supported = "The method does not work inside this connector."

and = "and"
decimal_point = '.'
thousands_sep = ','

######################
# Method permissions #
######################
err_type = "This method is restricted to %s."
err_stub = "This method is not implemented yet."
err_type_member = "Only members are allowed to execute this method. Please %s first, and then come back here."
link_login_before_continue = "authenticate"

################
# Server Error #
################
mt_base_server_error = "Server Error"
md_base_server_error = "The server made a booboo... probably broken code or a configuration error."

##############
# Fileserver #
##############
mt_base_file_server = "File Download"
md_base_file_server = "Download a file from this website."
