"%s" = "%s" # Do not delete :)
module_base = "Base"

err_web_param_wrong = "A method parameter could not parse for cmd %s. In context '%s'"
err_param = "Invalid value for parameter %s: %s"
err_method_connector_not_supported = "The method does not work inside this connector."
err_method_disabled = "This method is disabled here."
err_render_mode = "Invalid Render Mode: %s"
err_permission = "You need the %s permissions to execute this method."
err_permissions = "You are not allowed to access this method."
err_not_in_private = "This method does not work in private."
err_not_in_channel = "This method does not work inside channels."
err_not_authenticated = "Your account is not authenticated."

and = "and"
decimal_point = '.'
thousands_sep = ','
authenticate = "authenticate"

##############
# Decorators #
##############
err_rate_limit_exceeded = "You have exceeded the max of %s usages per %s. Please wait %s."
err_decorate_only_instance_methods = "Can only decorate instance methods. At best gdo_execute()."
##############
# GDO_Module #
##############
module_priority = "Priority"

######################
# Method permissions #
######################
err_type = "This method is restricted to %s."
err_stub = "This method is not implemented yet."
err_type_member = "Only members are allowed to execute this method. Please %s first, and then come back here."
link_login_before_continue = "authenticate"
err_type_guest = "You need to %s before you execute this method. It is also possible to %s."
link_continue_as_guest = "continue as guest"

################
# Server Error #
################
mt_base_server_error = "Server Error"
md_base_server_error = "The server made a booboo... probably broken code or a configuration error."

################
# Server Error #
################
mt_base_client_error = "Client Error"
md_base_client_error = "The server could not process your parameters."

##############
# Fileserver #
##############
mt_base_file_server = "File"
md_base_file_server = "Download a file from this website."

#############
# dirserver #
#############
mt_base_dir_server = "Directory"
md_base_dir_server = "List a directory on this server."
