"%s" = "%s" # Do not delete :)
module_base = "Base"

err_web_param_wrong = "A method parameter could not parse for cmd %s. In context '%s'"

################
# Server Error #
################
mt_base_server_error = "Server Error"
md_base_server_error = "The server made a booboo... probably broken code or a configuration error."

