import functools

from gdo.base.Render import Mode
from gdo.base.Util import html
from gdo.ui.IconProvider import IconProvider


class IconUTF8(IconProvider):

    @classmethod
    @functools.cache
    def MAP(cls) -> dict:
        return {
            'account': '⛁',
            'add': '✚',
            'address': '⌘',
            'alert': '!',
            'all': '▤',
            'amt': '#',
            'arrow_down': '▼',
            'arrow_left': '←',
            'arrow_right': '‣',
            'arrow_up': '▲',
            'audio': '🎵',
            'back': '↶',
            'bank': '🏦',
            'bars': '☰',
            'bee': '🐝',
            'bell': '🔔',
            'birthday': '🎂',
            'block': '✖',
            'book': '📖',
            'bulb': '💡',
            'business': ' 🏬',
            'calendar': '📅',
            'captcha': '♺',
            'caret': '⌄',
            'cc': '💳',
            'close': '✖',
            'code': '🗟',
            'construction': '🚧',
            'country': '⚑',
            'check': '✔',
            'color': '🎡',
            'copyright': '©',
            'create': '✚',
            'credits': '¢',
            'cut': '✂',
            'delete': '✖',
            'diamond': '❖',
            'done': '✔',
            'done_all': '✔',
            'download': '⇩',
            'edit': '✎',
            'email': '✉',
            'error': '⚠',
            'eye': '👁',
            'face': '☺',
            'female': '♀',
            'file': '🗎',
            'flag': '⚑',
            'flash': '🗲',
            'folder': '📁',
            'font': 'ᴫ',
            'format': 'F',
            'gender': '⚥',
            'group': '😂',
            'guitar': '🎸',
            'hands': '🤝',
            'heart': '♡',
            'help': '💡',
            'house': '🏠',
            'icecream': '🍦',
            'image': '📷',
            'info': 'ⓘ',
            'language': '⛿',
            'legal': '⚖',
            'level': '🏆',
            'license': '§',
            'like': '❤',
            'link': '🔗',
            'list': '▤',
            'location': '🚩',
            'lock': '🔒',
            'magic': '🪄',
            'male': '♂',
            'medal': '🥇',
            'menu': '≡',
            'message': '☰',
            'minus': '-',
            'money': '$',
            'name': '📛',
            'numeric': 'π',
            'password': '⚷',
            'pause': '⏸',
            'percent': '%',
            'phone': '📞',
            'plus': '+',
            'position': '🗺',
            'print': '🖶',
            'qrcode': '╬',
            'question': '?',
            'quote': '↶',
            'remove': '✕',
            'reply': '☞',
            'required': '❋',
            'schedule': '☷',
            'search': '🔍',
            'select': '🎚',
            'settings': '⚙',
            'shopping': '🛒',
            'spiderweb': '🕸',
            'star': '★',
            'stop': '❌',
            'sun': '🌞',
            'table': '☷',
            'tag': '⛓',
            'text': '🗟',
            'thumbs_up': '👍',
            'thumbs_down': '👎',
            'thumbs_none': '👉',
            'time': '⌚',
            'title': 'T',
            'trophy': '🏆',
            'unicorn': '🦄',
            'upload': '⇧',
            'url': '🌐',
            'user': '☺',
            'users': '😂',
            'view': '👁',
            'vote': '🗳',
            'wait': '◴',
            'whatsapp': '📱',
            'work': '👷',
            'write': '✎',
        }

    @classmethod
    def display_icon_html(cls, name: str, mode: Mode, alt: str, color: str = None, size: str = None) -> str:
        c = cls.MAP()[name]
        color = f" color: {color};" if color else ""
        size = f" font-size: {size};" if size else ""
        style = f' style="{color} {size}"' if color or size else ""
        return f'<span role="icon" aria-label="{html(alt)}"{style} class="gdt-icon">{c}</span>'
