module_account = "Account"
link_settings = "Settings"

############
# list_cli #
############
mt_account_list_cli = "Settings"
md_account_list_cli = "List your module settings."
msg_cli_settings = "Your settings: %s."

###########
# set_cli #
###########
mt_account_set_cli = "Set Setting"
md_account_set_cli = "Set and display a setting"
msg_print_cli_setting = "Your setting for %s is %s.%s for example: %s."
msg_set_cli_setting = "Your setting for %s changed from %s to %s."

################
# all_settings #
################
mt_account_all_settings = "All Settings"
md_account_all_settings = "Manage your user settings."

############
# settings #
############
mt_account_settings = "%s Settings"
md_account_settings = "Change %s settings."
setting_changed = "%s changed from %s to %s."
msg_settings_changed = "Your settings have been changed. %s"
