module_form = "Forms"

msg_form_submitted = "Your form has been sent successfully."
err_form_invalid = "The form you have sent is errorneous: %s"
err_csrf = "Your formular token is invalid, or you have sent the form twice. You could also have cookie problems."
